import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	changelogSidebar1: [{ type: "autogenerated", dirName: "v0.3.x" }],
	changelogSidebar2: [{ type: "autogenerated", dirName: "v0.2.x" }],
	changelogSidebar3: [{ type: "autogenerated", dirName: "v0.1.x" }],
};

export default sidebars;
